language: android
android:
  components:
   - tools
   - build-tools-25.0.2
   - android-25
   - extra-android-m2repository

jdk:
   - oraclejdk8

sudo: false

cache:
  directories:
   - $HOME/.m2

script: ./gradlew assembleRelease
